<?php
/**
 * Replaces the hand-written counter markup with a loop over the stats table.
 *
 * The digits are generated by site/partials/stat-counter.blade.php, because in
 * this template a number is a stack of scrolling columns rather than text.
 *
 * Run: php tools/wire_stats.php
 */

require __DIR__ . '/lib_slice.php';

$VIEWS = dirname(__DIR__) . '/resources/views/site/pages/';

$SCOPES = [
    'home' => 'home',
    'about' => 'about',
    'services' => 'service',
    'career' => 'career',
];

foreach ($SCOPES as $view => $scope) {
    $file = $VIEWS . $view . '.blade.php';
    if (! is_file($file)) {
        continue;
    }

    $html = file_get_contents($file);

    $run = [];
    $offset = 0;
    while (preg_match('#<div[^>]*class="(?:[^"]*\s)?about-us-info-item(?:\s[^"]*)?"#', $html, $m, PREG_OFFSET_CAPTURE, $offset)) {
        $start = $m[0][1];
        $end = match_close($html, $start, 'div');
        $run[] = [$start, $end];
        $offset = $end;
    }

    if (count($run) < 2) {
        printf("  %-12s skipped (found %d)\n", $view, count($run));
        continue;
    }

    $template = substr($html, $run[0][0], $run[0][1] - $run[0][0]);

    // swap the generated counter in for the frozen digit columns
    $item = preg_replace(
        '#(<div[^>]*class="(?:[^"]*\s)?about-us-info-title(?:\s[^"]*)?"[^>]*>).*?(</div>\s*<p)#s',
        '$1@include(\'site.partials.stat-counter\', [\'withBreak\' => $loop->first])$2',
        $template,
        1
    );

    $item = preg_replace(
        '#(<p class="gray-text">)(.*?)(</p>)#s',
        '$1{{ $stat->label }}$3',
        $item,
        1
    );

    $source = '\App\Models\Stat::forScope(\'' . $scope . '\')->ordered()->get()';
    $loop = '@foreach (' . $source . ' as $stat)' . $item . '@endforeach';

    $html = substr($html, 0, $run[0][0]) . $loop . substr($html, end($run)[1]);
    file_put_contents($file, $html);

    printf("  %-12s %d counters -> loop (scope: %s)\n", $view, count($run), $scope);
}
